function detectConstraints(message) {
  const text = String(message || '').toLowerCase();
  return {
    wantsRead: text.includes('leia') || text.includes('abra') || text.includes('readme'),
    wantsReadAgain: text.includes('leia de novo') || text.includes('leia novamente') || text.includes('abra novamente'),
    wantsList: text.includes('liste') || text.includes('arquivos') || text.includes('pastas'),
    wantsSearch: text.includes('busque') || text.includes('procure') || text.includes('grep'),
    wantsWrite: text.includes('crie o arquivo') || text.includes('salve') || text.includes('escreva no arquivo'),
    wantsAnalysis: text.includes('analise') || text.includes('resuma'),
    wantsMultiStep: /\b(e|depois|entao|então)\b/.test(text),
  };
}

function detectReferencedFile(message, retrievalContext) {
  const explicitMatch = String(message).match(/([A-Za-z0-9_./\\-]+\.(md|txt|json|js|ts|py|rs))/i);
  if (explicitMatch) {
    return explicitMatch[1];
  }

  if (retrievalContext?.recalled_artifact_path) {
    return retrievalContext.recalled_artifact_path;
  }

  if (retrievalContext?.semantic_match?.path) {
    return retrievalContext.semantic_match.path;
  }

  if (retrievalContext?.last_artifact?.path) {
    return retrievalContext.last_artifact.path;
  }

  return '';
}

function buildStep(sessionId, suffix, tool, agent, toolArguments, goal, extra = {}) {
  return {
    step_id: `${sessionId}:step:${suffix}`,
    selected_tool: tool,
    selected_agent: agent,
    tool_arguments: toolArguments,
    goal,
    ...extra,
  };
}

function planTask({ message, sessionId, retrievalContext = {}, runtimeConfig = {} }) {
  const constraints = detectConstraints(message);
  const steps = [];
  const referencedFile = detectReferencedFile(message, retrievalContext);

  if (constraints.wantsList) {
    steps.push(
      buildStep(
        sessionId,
        'list',
        'glob_search',
        'researcher_agent',
        { pattern: '**/*', path: '.' },
        'inspect workspace structure',
      ),
    );
  }

  if (constraints.wantsSearch) {
    const patternMatch = String(message).match(/["'`](.+?)["'`]/);
    steps.push(
      buildStep(
        sessionId,
        'grep',
        'grep_search',
        'researcher_agent',
        {
          pattern: patternMatch ? patternMatch[1] : 'TODO',
          path: '.',
          output_mode: 'content',
          head_limit: 20,
        },
        'search workspace content for requested pattern',
      ),
    );
  }

  if (constraints.wantsRead || constraints.wantsReadAgain || constraints.wantsAnalysis) {
    const chosenPath = referencedFile || 'README.md';
    steps.push(
      buildStep(
        sessionId,
        constraints.wantsAnalysis ? 'analysis-read' : 'read',
        'read_file',
        'researcher_agent',
        {
          path: chosenPath,
          limit: constraints.wantsAnalysis ? 160 : 120,
        },
        'retrieve target file contents',
      ),
    );
  }

  if (constraints.wantsWrite) {
    const targetPath = referencedFile || 'output.txt';
    steps.push(
      buildStep(
        sessionId,
        'write',
        'write_file',
        'coder_agent',
        {
          path: targetPath,
          content: 'Generated by Omini Phase 3 runtime.\n',
        },
        'persist requested content',
      ),
    );
  }

  if (steps.length === 0) {
    steps.push(
      buildStep(
        sessionId,
        'respond',
        'none',
        'master_orchestrator',
        {},
        'respond directly without tool use',
      ),
    );
  }

  return {
    constraints,
    max_steps: Math.min(runtimeConfig.maxSteps || 6, steps.length || 1),
    stop_on_error: true,
    retry_policy: {
      max_attempts: runtimeConfig.maxRetries || 1,
      backoff_ms: 0,
    },
    requires_review: steps.some(step => step.selected_tool !== 'none'),
    steps,
  };
}

module.exports = require('./advancedPlannerSpecialist');
